### ISSUE TITLE
XNet runtime parameters disjoint from Makefile vars and other runtime parameters

### ISSUE THREAD

**Issue by jaharris87** [starkiller-astro/Microphysics#118]
Examples:
`xnet_iscrn` --- `USE_SCREENING`
`xnet_ymin` --- `small_x`
`xnet_iheat` --- `do_constant_volume_burn`, `burning_mode`
no XNet parameter --- `call_eos_in_rhs`
`xnet_tolm`, `xnet_tolc`, `xnet_tolt9` --- `rtol*`
`xnet_idiag` --- `burner_verbose`

**Comment by zingale** [comment]
we've diverged a lot from XNet, and it doesn't support our GPU or SDC strategy, so I am closing.
