### ISSUE TITLE
Clarify wion in aprox13

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#122]
In aprox13, and possibly other networks as well, when we initialize the network variables in actual_network we have:

```
    ! Molar mass                                                                                                                                                                              
    wion(:) = avo * mion(:)

    ! Common approximation                                                                                                                                                                    
    wion(:) = aion(:)
```

Instead of setting `wion` twice, we should think about which of these to use, as `mion` incorporates the binding energy as well.

**Comment by maxpkatz** [comment]
`wion` is not actually used in any aprox13 calculation. Maybe we should just sidestep the issue by deleting it?

**Comment by zingale** [comment]
I agree -- delete it!

**Comment by zingale** [comment]
looks like a lot of networks define this.
