### ISSUE TITLE
need an actual_rhs_finalize()

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#134]
We need an `actual_rhs_finalize()` to deallocate anything that was allocated in `actual_rhs_init()`

**Comment by zingale** [comment]
in particular, networks like `aprox13` create a table via `create_rates_table` and we should clean up after those.

**Comment by zingale** [comment]
the aprox_rates also allocates storage that we should clean up

**Comment by maxpkatz** [comment]
This is a non-issue at this point -- because we are using global variables for this data now, they will automatically get cleaned up at program exit. We can always revisit if we change that approach.
