### ISSUE TITLE
Get unit tests running on the GPU again

### ISSUE THREAD

**Issue by maxpkatz** [starkiller-astro/Microphysics#138]
The merge of #135 means we need to get the C++ drivers for test_eos and test_react working on the GPU.

**Comment by zingale** [comment]
We should try to get this going before the hackathon (@dwillcox, @maxpkatz  -- do you want me to give it a shot?)

**Comment by dwillcox** [comment]
I was just looking at that today and realized I needed to do that. You're welcome to give it a shot, but otherwise I'll do it.

**Comment by dwillcox** [comment]
The drivers for test_eos and test_react both work on the GPU now as of 0d65d1d5.
