### ISSUE TITLE
reconsider eos_input_is_constant

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#140]
helmeos has a runtime parameter `eos_input_is_constant` set to `.false.` by default.  This comes input play when we are inverting the EOS.  Say we come in with e and rho and find T.  Because we were finding to a specified tolerance (1.e-8 in helmeos), the T that we converge to when used as input to the EOS will not give us the e that we come in with.   What this does (as `.false.`) is reset e to the result returned from the EOS.  This is a very small change, but it can overwhelm convergence when trying to do everything to 4th order.  It also doesn't seem like the right default, since e is a more fundamental hydro variable than T.

**Comment by maxpkatz** [comment]
This was addressed in #154, closing.
