### ISSUE TITLE
create python bindings for the EOS

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#142]
we should be able to use the starkiller EOSes from python

**Comment by zingale** [comment]
one trick here will be how to let python set the runtime parameters

**Comment by dwillcox** [comment]
The solution for this in `python_library` is to initialize the StarKillerMicrophysics module by passing it the name of a probin file that is read using the runtime parameter interface in `extern.F90`.

With that approach we still might want to pass parameters from python, e.g. if we want to determine the behavior of the EOS or burner with a scripted variation in runtime parameters.

For that, it is possible to do the following:

```
>>> import StarKillerMicrophysics
>>> skinit = StarKillerMicrophysics.starkiller_initialization_module
>>> skinit.starkiller_initialize("probin.ignition")
 
 Initializing Helmholtz EOS and using Coulomb corrections.
 
>>> extern = StarKillerMicrophysics.extern_probin_module
>>> extern.eos_dtol
1e-08
>>> extern.eos_dtol = 1.0e-6
>>> extern.eos_dtol
1e-06
>>>
```

**Comment by zingale** [comment]
@dwillcox isn't this done?  Why did you reopen?

**Comment by dwillcox** [comment]
No idea why I reopened, but this indeed works and a sample python script that queries the EOS is provided here:

`Microphysics/python_library/StarKiller/StarKiller/examples/call_eos.py`

I should document this interface and organize the examples a bit, closing this issue though.
