### ISSUE TITLE
burn_cell crashes in debug, floating-point exceptions

### ISSUE THREAD

**Issue by sandshrews** [starkiller-astro/Microphysics#143]
Compile `unit_test/burn_cell` with `ignition_reaclib/URCA-simple` in debug mode (`NDEBUG=  `) and find error:

 Completed burn to:    1.0000000000000000       seconds

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7F93A27C9E08
#1  0x7F93A27C8F90
#2  0x7F93A1EFA4AF
#3  0x7F93A28A1661
#4  0x7F93A289A7BC
#5  0x4051C8 in write_burn_t_ at main.f90:195 (discriminator 10)
#6  0x4067F7 in MAIN__ at main.f90:116
Floating point exception (core dumped)

**Comment by zingale** [comment]
do a `pull` and try again -- I think it is fixed now.
