### ISSUE TITLE
screen5 blend is unneeded

### ISSUE THREAD

**Issue by rjfarmer** [starkiller-astro/Microphysics#149]
Hi,
The screening in screen.f90 line ~ 477 
>if (gamefs - gamef .lt. blend_frac*(gamefs - gamefx)) then

is wrong, its screening the intermediate to strong but the intermediate is already a blend between the weak/strong regimes so it doesn't need another blend on top (and it doesn't even do the blend properly anyway, you need a dalfadt and dbetadt in the dh12dt expression). There is a corrected fix in mesa's screen.f90 file for this in version 9831:
https://sourceforge.net/p/mesa/code/9831

**Comment by zingale** [comment]
note: we also have a different value of `h12_max` -- we have `30.0` while MESA has `300.0`.

**Comment by zingale** [comment]
differences are O(1.e-3) to O(1.e-5):

http://bender.astro.sunysb.edu/Microphysics/test-suite/test-suite-gfortran/2018-09-05-002/index.html

**Comment by adam-m-jcbs** [comment]
For what it's worth, Kepler also uses `h12_max = 300.0`.

**Comment by zingale** [comment]
this has been fixed.
