### ISSUE TITLE
Logo for StarKiller-Astro organization

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#161]
We don't have a pretty logo for the StarKiller-Astro organization and obviously this is an essential priority :-)

So I thought we could brainstorm a little, please comment!

I was thinking if we zoom in to the XRB flame in the abar plot that might look cool.

**Comment by zingale** [comment]
we should have one before the Jan AAS meeting?

**Comment by dwillcox** [comment]
sounds good to me

**Comment by zingale** [comment]
closing since we're moving this repo
