### ISSUE TITLE
Add weaklib interface to documentation

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#198]
We should document the weaklib interface.

Needed for #197

**Comment by jaharris87** [comment]
stellarcollapse is the most similar existing interface.

When you say document, are you meaning on the level of a ReadMe, e.g. https://github.com/starkiller-astro/Microphysics/blob/master/EOS/stellarcollapse/README ?

Or a section in the User's Guide (e.g. 4.1.6)?

Probably at least both, but more?

**Comment by zingale** [comment]
it would be good to be in the User's Guide.  That just involves hacking the sphinx source.  Travis handles the rest.

**Comment by zingale** [comment]
this is quite old now, and I think we've drifted far from this, so I am closing unless someone is interested in taking this on
