### ISSUE TITLE
need to reevaluate the tolerances

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#20]
We ask for species to be evolved to a tolerance of 1.d-12 (in `integration/_parameters`).

This is pretty tight.  We need to check whether it can be relaxed.  We can relax on a network-by-network basis (using priorities in the `_parameter` files).  

It seems that the original aprox13 and aprox19 networks used tolerances of 1.e-6

**Comment by zingale** [comment]
note also that the `BS` integrator has only a single tolerance -- it takes the max of all the tolerances:

```
    bs % atol(:) = 0.d0                                                         
    bs % rtol(:) = max(rtol_spec, rtol_temp, rtol_enuc)                         
```

**Comment by zingale** [comment]
the way to properly do this is to look at convergence of the results as we tighten the tolerances for each burner / integrator.

**Comment by zingale** [comment]
there is some thought on this in the wdmerger II paper.  It seems that 1.e-8 should be okay...

**Comment by zingale** [comment]
I think that @abigailbishop largely has done this.  We should add some plots to the user's guide

**Comment by abigailbishop** [comment]
I can do that.

**Comment by zingale** [comment]
I think we've mostly addressed this now.
