### ISSUE TITLE
smarter tolerance loosening

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#231]
I think we should change the way we loosen tolerances when we do retires.  For example, suppose that

rtol_spec = 1.e-8
rtol_temp = 1.e-5

should we loosen them both by the same amount? or should we start by loosening the tightest (spec)?  Perhaps we should have a minimum tolerance we are willing to live with.

**Comment by maxpkatz** [comment]
A cause for prudence here is that if we guess wrong and really we needed to loosen both to get the final answer, we'll end up doing more retries, perhaps many more. However I do like the idea of having a tolerance floor.

**Comment by zingale** [comment]
okay, I'll implement the floor.

**Comment by zingale** [comment]
I think we decided to have the hydro algorithm handle the retries now, so we probably don't need to worry about this
