### ISSUE TITLE
create an NSE solver

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#232]
We should be able to solve for the equilibrium species from a network but solving the nonlinear system dY/dt = 0 for a given network.  We have pretty much all of the pieces in place for this in our integrators (including the Jacobian).

If we have an NSE interface, we can use that at problem initialization when mapping an initial model onto the grid to reset the nuclei to initially be in equilibrium.

**Comment by adam-m-jcbs** [comment]
Assigning myself to help keep my eye on this issue.  Also, adding some relevant context from @maxpkatz :

> Doron Kushnir submitted a rather interesting paper to arXiv recently that discusses a method for dynamically identifying groups in the network that are in effective NSQE and then doing an algebraic solve on them, with a normal burn on all other isotopes (https://arxiv.org/abs/1912.06151)

This could be useful to consider when developing an NSE solver

**Comment by zingale** [comment]
closing this since we have the NSE table #327
