### ISSUE TITLE
create C++ EOSes

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#242]
To move Castro's hydro off of Fortran, we need a C++ EOS.  There are a few approaches we can consider:

  1. Make a separate implementation of each EOS in C++, so we would have a separate complete Fortran and C++ EOS routines.

  2. Create a C++ wrapper to the existing EOSes.  It might be hard to keep the current Fortran derived type, so we might need an intermediate interface that accepts a C++ struct and unpacks it into the Fortran type.

3. Get rid of the Fortran implementations completely and rewrite all the EOSes in C++.  Then, if needed, we could create Fortran interfaces to call the C++

**Comment by maxpkatz** [comment]
I prefer option 1 since we cannot move everything to C++ at one time. I do not believe we spend that much time on EOS maintenance, and it sounds less tricky than getting Fortran to C++ (or vice versa) interfaces correct.

**Comment by maxpkatz** [comment]
The interface for C should mirror Fortran; the eos_t is a C struct, and we still do eos(input, state).

**Comment by zingale** [comment]
the framework for this has been merged.  Now it's just adding semi-colons ;)
