### ISSUE TITLE
VODE optimizations

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#251]
We should look more deeply at memory usage in VODE and optimize it as best we can.  Some thoughts:

1. why do we need to store abar, zbar, eta, ye in rpar?
2. is it worth it to change the burner code to store a generic specific heat, cx, instead of both cp and 
    cv and their derivatives?  This will save 2 double precision numbers
3. does self_heat change on a zone-by-zone basis?  So we really need to store that in rpar and 
    pass it all through everywhere, copying it back and forth each time we convert between burn_t 
    and rpar?
4. why do we store irp_y_init at all? it doesn't seem we use that

**Comment by maxpkatz** [comment]
I don't remember this code well enough to answer 1 and 4. For 2, yes I'd support that; though the memory saving isn't substantial, it would make `temperature_rhs` and `temperature_jac` simpler if we didn't have to have separate code paths for constant volume and constant pressure. For 3, it can change on a zone-by-zone basis if we're using "hybrid" mode (burning_mode == 2).

**Comment by zingale** [comment]
I think there are a lot of places where we initialize things to 0 twice in succession, e.g. in `vode_rhs`, we set `ydot = 0`, and then the first thing we do in `actual_rhs` (for aprox13, e.g.) is set `ydot = 0`.  I think we should take the approach that the network is responsible for ensuring `ydot` is valid and if it needs to initialize `ydot = 0`, then it should on its own

**Comment by zingale** [comment]
I implemented 2 in #260 , but it doesn't seem worth it.

**Comment by zingale** [comment]
most of these have been done
