### ISSUE TITLE
need GPU tests in the regression test suite

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#27]
We have no GPU tests in the PGI test suite.  We should pick some basic tests to add coverage.

**Comment by zingale** [comment]
@dwillcox can you suggest a problem that uses the CUDA VODE for the test suite?  Please give the make line.

**Comment by dwillcox** [comment]
Here are the 3 networks I've set up with CUDA VODE.

**ignition_simple**

Make line:

`make -j COMP=PGI NDEBUG=t MPI= OMP= CUDA=t NETWORK_DIR=ignition_simple INTEGRATOR_DIR=VODE90 EOS_DIR=helmholtz BL_USE_F_BASELIB=t`

Execute Line:

`./main.Linux.PGI.exe inputs_ignition.32`

**ignition_reaclib/URCA-simple**

Make Line:

`make -j COMP=PGI NDEBUG=t MPI= OMP= CUDA=t NETWORK_DIR=ignition_reaclib/URCA-simple INTEGRATOR_DIR=VODE90 EOS_DIR=helmholtz BL_USE_F_BASELIB=t`

Execute Line:

`./main.Linux.PGI.exe inputs_reaclib_urca.32`

**aprox13**

Make Line:

`make -j COMP=PGI NDEBUG=t MPI= OMP= CUDA=t NETWORK_DIR=ignition_reaclib/aprox13 INTEGRATOR_DIR=VODE90 EOS_DIR=helmholtz BL_USE_F_BASELIB=t`

Execute Line:

`./main.Linux.PGI.exe inputs_aprox13.32`

**Comment by dwillcox** [comment]
amrex branch is `gpu`

Microphysics branch is `cudadevice`

**Comment by zingale** [comment]
ah... I think I need to wait until it is all in `development`

**Comment by zingale** [comment]
there is now a nightly GPU test suite
