### ISSUE TITLE
burning_mode = 0 and 1 can be removed

### ISSUE THREAD

**Issue by maxpkatz** [starkiller-astro/Microphysics#300]
They are redundant with the `integrate_temperature` option, and that one is much easier to understand what it does.

**Comment by maxpkatz** [comment]
Also, burning_mode = 2 (which retries a burn with temperature integration turned off if the self-heating burn fails) is not necessary now that Castro has retries, and burning_mode = 3 is not something we want to use in the long run anyway (it was an experiment to see if we want to use the burning limiters in the literature, and we do not), so we can just ditch the burning_mode parameter entirely.

**Comment by zingale** [comment]
I'm confused by the title -- we don't want to remove burning_mode = 1, which is the default, but instead that is just going to be the only mode, right?

**Comment by maxpkatz** [comment]
> 
> 
> I'm confused by the title -- we don't want to remove burning_mode = 1, which is the default, but instead that is just going to be the only mode, right?

Correct, I'm talking about removing the parameter, not the physics.
