### ISSUE TITLE
Include fundamental constants in this repo?

### ISSUE THREAD

**Issue by jaharris87** [starkiller-astro/Microphysics#31]
Currently this would be inconsistent with some EoS tables that are pre-generated with a specific set of constants, but could still be useful in the long-run for separate codes to have a shared set of constants.

**Comment by cmsquared** [comment]
For whatever my opinion is worth, I have thought this was a good idea for quite some time (before there was a separate microphysics repo)...

**Comment by zingale** [comment]
this is also useful for the different networks.  Currently:

* `ignition_simple` has constants hardcoded in
* `ignition_reaclib` has its own constants module
* `aproxXX` have their own physical constants hardcoded in

**Comment by dwillcox** [comment]
bumping this to remind myself - this would be useful for having only one place to update recommended values ...

pynucastro contains both CODATA 2014 and CODATA 2006 values

Helmholtz EOS contains CODATA 2006 values

Now there is a CODATA 2018 ... http://pdg.lbl.gov/2019/reviews/rpp2018-rev-phys-constants.pdf

Differences among all 3 for e.g. Avogadro's number are <1 part in 10^7, but it would be nice to be consistent and current.

**Comment by zingale** [comment]
the trick with Helmeos is that if you change those values, you should really change the data table itself, since it was computed with a specific set of constants.

**Comment by dwillcox** [comment]
ah good point - that reminds me we've wished to be able to generate our own custom Helmeos tables from time to time.

**Comment by zingale** [comment]
the constants are now part of this repo
