### ISSUE TITLE
Simplified SDC tolerances are not density-scaled

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#310]
Currently we take `atol_spec` and `atol_enuc` from the inputs as for Strang, and then apply these tolerances to `rho*X` and `rho*E` (or `rho*h` for `SDC_EVOLVE_ENTHALPY`).

We should scale these tolerances by `rho_min`, where:

`rho_min = min(rho(0), rho(0) + rho_advective_source * dt)`

where `dt` is the integration time.

**Comment by zingale** [comment]
this has been resolved
