### ISSUE TITLE
OpenACC F90 test_react w/ ignition_simple & VBDF giving ptx errors

### ISSUE THREAD

**Issue by adam-m-jcbs** [starkiller-astro/Microphysics#35]
Building `test_react` with
```
make COMP=PGI NDEBUG= OMP= NETWORK_DIR=ignition_simple INTEGRATOR_DIR=VBDF ACC=t
```

Errors like the following come up:
```
ptxas /tmp/pgaccBw5JrAtcYokR.ptx, line 1842; fatal   : Parsing error near '-': syntax error
ptxas fatal   : Ptx assembly aborted due to errors
PGF90-S-0155-Compiler failed to translate accelerator region (see -Minfo messages): Device compiler exited with error status code (../../integration/VBDF/actual_integrator.F90: 1)
  0 inform,   0 warnings,   1 severes, 0 fatal for 
make: *** [t/Linux.PGI.debug.acc/o/actual_integrator.o] Error 2
make: *** Waiting for unfinished jobs....
```

Through commenting out and slowly uncommenting, I've traced at least one triggering of the error to a derived type assignment in `Microphysics/integration/VBDF/actual_integrator.F90` in the `initial_timestep()` subroutine: `ts_temp = ts`.

However, after writing and using a copy subroutine for `bdf_ts` types, the error continues.  It seems any use of `ts_temp` triggers the error, even `ts_temp%neq = 1`.

**Comment by adam-m-jcbs** [comment]
Max played with it and found that the error seems to be a pretty fundamental error in how PGI's generating ptx code.  A bug report has been filed.

**Comment by maxpkatz** [comment]
Fixed by adding -ta=tesla:cuda8.0
