### ISSUE TITLE
allow for Fortran building to be disabled

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#453]
We should start wrapping the EOS and Reaction stuff so that we can optionally skip compiling them.

We can do this either with separate `USE_F90_EOS`, `USE_F90_REACTIONS`, ... to enable/disable different parts or through a single `USE_F90_MICROPHYSICS`, to turn off all of F90 (eventually).

**Comment by maxpkatz** [comment]
For reactions a consideration is that we have a mix of networks with C++ or Fortran support and so USE_F90_REACTIONS may have to be conditional on which network you're using (for now).

**Comment by maxpkatz** [comment]
This now exists and is used in several tests. We cannot completely turn off Fortran yet because we still have some Fortran pynucastro networks, but after those are removed we can finish the Fortran elimination.
