### ISSUE TITLE
make call_eos_in_rhs permanently on and remove T integration

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#471]
Right now, we solve: dX/dt, dT/dt, and de/dt.  The latter 2 are redundant.  We integrate e to accumulate the energy release over the burn (taking into account neutrino loses, etc).  And we integrate T to get an updated temperature to evaluate the rates during the subcycling of the integration.  Additionally, the reason for `call_eos_in_rhs` is to update the specific heats needed for the T integration.   But all that really does is do `eos(rho, T) -> c_v`.

A more consistent way to do things would be to just integrate dX/dt and de/dt and then always call the eos to get T from rho, e.  This will eliminate 1 equation from the ODE system and could make the overall integration easier.

Note:
* This only applies to Strang integration.  For the various types of SDC integration we are effectively already doing this.
* We would need to cast the analytic Jacobian in terms of e -- we can follow the model used for simplified SDC to translate it to the correct independent variables.  That works very well for simplified SDC.

**Comment by zingale** [comment]
This would also make it a lot easier to eventually merge the simplified SDC and Strang integrators

**Comment by maxpkatz** [comment]
It is looking like #470 would significantly cut down on Helmholtz EOS evaluation cost inside the burner. So we'll probably be more accurate than before without a significant performance overhead, and so we should do this.
