### ISSUE TITLE
intercept burn failure if we go into NSE

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#577]
Because we evolve T during the course of a burn, we can encounter the situation where over a timestep when integrating with aprox19, we evolve into the conditions where NSE applies.  The integrator usually fails in this case (with "too many steps") but on output, it shows that X(Si) <~ 0.01 and T >~ 6.e9 K, so we should be using NSE.

We should recognize this and use the NSE table in this situation to do the burn and then mark the burn as successful.

**Comment by maxpkatz** [comment]
A more general version of this would be to check for the NSE conditions at every timestep in the burn and immediately set the NSE conditions and return if they are satisfied.

**Comment by zingale** [comment]
It seems the easiest way to do this is to let the burn fail, but detect the failure before returning back to Castro.  In that case, we have an initial state send from Castro: (t0, Y0) and a state left behind by the integrator when it failed to finish (t*, Y*).

So the question is do we do the NSE from (t0, Y0) or do we do it from (t*, Y*) and add the energy release to that left behind from the incomplete burn?

**Comment by zingale** [comment]
yes, we could detect this in the RHS, set NSE, and then kick out of the burn with it marked as successful.  I think either approach should work.

**Comment by maxpkatz** [comment]
> So the question is do we do the NSE from (t0, Y0) or do we do it from (t*, Y*) and add the energy release to that left behind from the incomplete burn?

I don't think we can really make an argument that the latter is better than the former, since the NSE cutoff is a hard cutoff, so the former sounds better because it is easier.

**Comment by zingale** [comment]
I think I agree -- we're making the argument that it doesn't matter how we got there, the energy release still reflects the change in binding energy / nucleon.

**Comment by maxpkatz** [comment]
Yes.

**Comment by zingale** [comment]
this was implemented in #628
