### ISSUE TITLE
Profile the SDC implementation in the Microphysics integrators

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#60]
Max has suggested we profile the SDC integration to determine how expensive the EOS calls really are.

The motivation for this is that the EOS calls use rho, e as input variables and it may be worthwhile to think about how to formulate T integration source terms so we could use rho, T as input variables to the EOS instead.

The cost of the EOS should be more apparent using tabulated rates, so this is related to issue #12

**Comment by zingale** [comment]
I don't think that this is needed anymore with the new set of integration variables
