### ISSUE TITLE
esum is slow

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#61]
We use `esum()` to do exact sums of specific terms in the RHS of the ODEs to prevent roundoff.  But `esum()` is slow.  At the moment, we have a general routine with a large `max_esum_size` -- this also causes trouble on the GPUs.  

We should experiment with creating specific `esum()` routines for the number of terms involved, e.g., `esum3()`, `esum4()`, `esum5()`, ...

We know this ahead of time, since we are explicitly calling `esum()` on specific combination of terms in rate equations.

**Comment by zingale** [comment]
we should also try to mark this function as `pure` and get it inlined

**Comment by zingale** [comment]
the `esum` algorithm comes from here: https://people.eecs.berkeley.edu/~jrs/papers/robustr.pdf

**Comment by zingale** [comment]
it is also not clear if `enum` makes sense with just 2 numbers.  Is it really better than just `a + b`

**Comment by zingale** [comment]
the `esum` branch removes all the `esum()` calls with 2 elements in `aprox13`.  This gives identical results to the original version when using `test_react` (as compared with `fcompare`).  This suggests that for 2 elements, it does not matter.

The code is about 3% faster w/o the `esum()` on 2 elements.  

I'm going to try to do a custom sum for 3 elements next.

**Comment by zingale** [comment]
PR #65 addresses some of this

**Comment by zingale** [comment]
should this still be open?

**Comment by maxpkatz** [comment]
I think it should still be open. We still have improvements we can make.

**Comment by maxpkatz** [comment]
Closing, I've done all I plan to do on esum at the moment -- the optimizations we've already thought of have been done, and new ones can be in a new issue.
