### ISSUE TITLE
Vectorize helmholtz EOS!

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#62]
The helmholtz EOS can represent a significant computational cost. We could consider vectorizing it.

**Comment by zingale** [comment]
we should also mark the `h5` function as `pure`, and we can do the same for the functions like `xpsi0` -- these should also be marked `elemental`

**Comment by zingale** [comment]
we don't think this is worth doing in Fortran anymore.  On the GPU, the EOS cost is small now.
