### ISSUE TITLE
Migrate Test Suite to C++

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#66]
Since MAESTRO is now moving to the C++ AMReX, we should migrate the test suite drivers in Microphysics to use the C++ AMReX as well.

A good starting point is `test_react` in Castro.

**Comment by zingale** [comment]
I've started this on the `cxx-buildsystem` branch using the AMReX tutorials as a guide.  I started with `test_eos`

**Comment by zingale** [comment]
the `burning_mode=0` issue happens with the old build system too (#137)

**Comment by zingale** [comment]
this was done in #135
