### ISSUE TITLE
abort_on_failure never used?

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#667]
We have the runtime parameter abort_on_failure, but it does not seem that we use it any more.

In Castro, we take pains to override this in certain situations, so that Castro logic might be doing nothing.

**Comment by maxpkatz** [comment]
Yes this is a good point. So if a burn fails in Maestro today, are we just continuing along merrily as if nothing happened?

**Comment by maxpkatz** [comment]
This was in the Fortran integrator.F90 right up until the Fortran was removed. So it was just an oversight that we didn't have the abort code path in integrator.H.
