### ISSUE TITLE
we should update VODE90 from linpack to lapack

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#70]
VODE90 currently uses linpack (since that's what VODE used originally).  We should switch it over to lapack so we can use system-optimized lapack routines.  This shows the lapack equivalent functions:

http://www.netlib.org/lapack/lug/node147.html

(note, the table has routines starting with `s` for single precision, but ours, of course, use `d`)

**Comment by maxpkatz** [comment]
The main thing to be aware of here is that for CUDA there isn't a system implementation of e.g. dgetrf we can simply link against the way we would do this for standard CPU builds. So we must provide at least one hand-written implementation for this case. (There is a library called cuSOLVER which implements LAPACK-like interfaces, but it's designed to be called from the host, not the device.)

**Comment by zingale** [comment]
we don't want to do this.
