### ISSUE TITLE
Reconcile VODE, VODE90 usage of `ydot`, `jac` in `burn_t` with that of BS, VBDF

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#78]
BS and VBDF both return the rhs and jacobian in `burn_t % ydot` and `burn_t % jac`, respectively. Neither VODE nor VODE90 do this, so for debugging purposes if those are needed they have to be printed from within the integration routines.

We should store the rhs and jacobian for VODE, VODE90 in `burn_t` in the subroutine `vode_to_burn` in `vode_type.f90`.

This is a bit complicated because `vode_integrator` doesn't have access to the rhs and jacobian, those are internal to both VODE and VODE90.

This will be easier to address once #69 is resolved because the rhs and jacobian are stored in `rwork_t`.

**Comment by zingale** [comment]
there are a lot of changes to how we handle the state in the VODE stuff now, and this is no longer relevant
