### ISSUE TITLE
add 14N(a,g)18F(a,p)21Ne and 12C(p,g)13N(a,p)16O rates to a net

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#84]
Following Shen and Bildsten 2009, we should include these rates for He det stuff.

**Comment by zingale** [comment]
paper ref: http://iopscience.iop.org/article/10.1088/0004-637X/699/2/1365/pdf

**Comment by zingale** [comment]
basic idea is that there will be some 14N around from accretion

during explosive phase, 14N(a,g)18F(a,p)21Ne takes place, freeing a proton to then react on  12C(p,g)13N(a,p)16O, which occurs faster than 12C(a,g)16O.

We may not need the 13N in the net.

This net would certainly be needed for the explosive phase.

**Comment by zingale** [comment]
For starters, we could just put together a net via pynucastro with:

p
He4
C12
N13
N14
O16
F18
Ne21

**Comment by dwillcox** [comment]
We should add a pynucastro feature that lets us specify nuclides and get all the rates linking them.

**Comment by dwillcox** [comment]
It would not be difficult, we'd just need to generate a set of RateFilters and loop through the Library once then discard rates involving nuclei not in the network.

pynucastro can already filter based on multiple RateFilter objects in a single pass through the Library, I just didn't demonstrate that feature in the examples.

The only other thing we need is a function to discard rates appropriately.

**Comment by zingale** [comment]
A version of this net using pyreaclib was created and is now in `networks/subCh`
