### ISSUE TITLE
CUDA VODE doesn't work with latest amrex gpu branch

### ISSUE THREAD

**Issue by dwillcox** [starkiller-astro/Microphysics#87]
On summitdev, run the test react problem with the `ignition_reaclib/C-burn-simple` network, helmholtz EOS, and VODE90 integrator compiled with PGI 17.10 and CUDA 9.0.69.

The following error is returned:

```
0: DEALLOCATE: unspecified launch failure
```

This is with the tip of the amrex gpu branch: 0c1a90b955b26f71cfd0f6729581401a0af5c846

This test problem works with the following hash on the amrex gpu branch: 23486c89f022a276af249514a91480b7663379a6

**Comment by maxpkatz** [comment]
What branch?

**Comment by dwillcox** [comment]
The `cudadevice` branch of Microphysics. I'm just getting back to this now and will see if I can determine what changed.

**Comment by dwillcox** [comment]
Closed via https://github.com/AMReX-Codes/amrex/pull/220
