### ISSUE TITLE
numerical jacobian may not be doing the species term correctly?

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#92]
We seem to be computing d(Ydot)/dX in `numerical_jacobian.f90` -- it is not clear we should be mixing mass and molar fractions here.

**Comment by maxpkatz** [comment]
I think you are correct and this is in error and perhaps always has been. We need to multiply state_del and state_delm by aion when coming out of actual_rhs, as we normally do in all the other calls to it.

**Comment by zingale** [comment]
merged #100
