### ISSUE TITLE
ener_gener_rate should always appear in the same module

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#97]
It seems the pynucastro nets put `ener_gener_rate` in `actual_network.f90`, which most others have it in `actual_rhs.f90`.  This makes it hard to use this routine outside of a net.  We should always put it in the same place.

**Comment by zingale** [comment]
@dwillcox can we chat about this together?

**Comment by dwillcox** [comment]
I've fixed this in pynucastro. See PR #98 for an updated version of subch.

**Comment by dwillcox** [comment]
At the moment, this is only on the development branch of pynucastro.

**Comment by zingale** [comment]
what about the Urca nets?

**Comment by zingale** [comment]
it looks like this still affects:

ignition_reaclib/C-test
ignition_reaclib/URCA-simple
ignition_reaclib/C-burn-simple

**Comment by maxpkatz** [comment]
When do we use `ener_gener_rate` outside of the RHS?

**Comment by zingale** [comment]
I no longer remember.  Probably in one of the unit tests

**Comment by maxpkatz** [comment]
OK. I chose not to implement `ener_gener_rate` explicitly in the C++ port of powerlaw, we can explicitly implement that at some point if we need.

**Comment by zingale** [comment]
I no longer think that this is an issue.
